image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin
  - git submodule update --init --recursive
before_build:
  - cmd: |
      mkdir build
      cd build
      cmake --version
      cmake .. -G "Visual Studio 15 2017 Win64"
build:
  project: build\SnailSnap.sln
  verbosity: minimal
  parallel: true
