sudo: false 
dist: trusty
language: generic

os: linux
env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
addons:
  apt:
    packages:
      - g++-5
      - qt510base
      - qt510multimedia
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'

script:
  - /opt/qt510/bin/qt510-env.sh
  - cmake . -DQt5_DIR=$QTDIR/lib/cmake/Qt5
  - make
